{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOJYEOxZt0PtwvLIp3hELcz",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sunainatarimela/CapstoneProject/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "7T65ja-mT8ih"
      },
      "outputs": [],
      "source": [
        "#%%writefile app.py\n",
        "import streamlit as st\n",
        "import streamlit.components.v1 as components\n",
        "\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import pickle\n",
        "import matplotlib.pyplot as plt\n",
        "import requests, os\n",
        "import base64\n",
        "\n",
        "apptitle = 'Gov Contracts'\n",
        "st.set_page_config(page_title=apptitle, page_icon=\":book:\")\n",
        "\n",
        "def get_base64(bin_file):\n",
        "    with open(bin_file, 'rb') as f:\n",
        "        data = f.read()\n",
        "    return base64.b64encode(data).decode()\n",
        "\n",
        "def set_background(png_file):\n",
        "    bin_str = get_base64(png_file)\n",
        "    page_bg_img = '''\n",
        "    <style>\n",
        "    .stApp {\n",
        "    background-image: linear-gradient(rgba(255,255,255,0.85), rgba(255,255,255,0.85)), url(\"data:image/png;base64,%s\");\n",
        "    background-size: cover;\n",
        "    }\n",
        "    </style>\n",
        "    ''' % bin_str\n",
        "    st.markdown(page_bg_img, unsafe_allow_html=True)\n",
        "set_background(\"/content/drive/MyDrive/IDS560/govcontracts.jpg\")\n",
        "\n",
        "\n",
        "def intro():\n",
        "    import streamlit as st\n",
        "\n",
        "    st.write(\"# Welcome Government contract data prediction during a pandemic\")\n",
        "    st.sidebar.success(\"Select an option above.\")\n",
        "\n",
        "    st.markdown(\n",
        "        \"\"\"\n",
        "        **Welcome!\n",
        "\n",
        "        Government Contracts are contracts that are given to various vendors to complete the task at hand. There are some contracts that are\n",
        "        released everyday depending on the need of the related government agency.\n",
        "\n",
        "        One of the websites to get updated government contracts related information is [sam.gov](https://sam.gov/content/home)\n",
        "\n",
        "        If you are a vendor for government contracts and want to see details about the contract assignments, then you are at the right place!\n",
        "\n",
        "        **👈 Select an option from the dropdown on the left to see the business type that would win a contract **\n",
        "    \"\"\"\n",
        "    )\n",
        "                                                              # \"\"\"THIS ONE WORKS\"\"\"\n",
        "def business_type_predict():\n",
        "    import pandas as pd\n",
        "    import numpy as np\n",
        "    import pickle\n",
        "    import matplotlib.pyplot as plt\n",
        "    import requests, os\n",
        "    import base64\n",
        "    import streamlit as st\n",
        "    import streamlit.components.v1 as components\n",
        "\n",
        "    # # Load the serialized object from the pickle file\n",
        "    # with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "        # label_encoders = pickle.load(file)\n",
        "\n",
        "        # NAICS Code Dictionary\n",
        "        # Naics_Dict = {'11':'Agriculture, Forestry, Fishing and Hunting',\n",
        "        # '21':'Mining',\n",
        "        # '22':'Utilities',\n",
        "        # '23':'Construction',\n",
        "        # '31':'Manufacturing',\n",
        "        # '32':'Manufacturing',\n",
        "        # '33':'Manufacturing',\n",
        "        # '42':'Wholesale Trade',\n",
        "        # '43':'Wholesale Trade',\n",
        "        # '44':'Retail Trade',\n",
        "        # '45':'Retail Trade',\n",
        "        # '48':'Transportation and Warehousing',\n",
        "        # '49':'Transportation and Warehousing',\n",
        "        # '51':'Information',\n",
        "        # '52':'Finance and Insurance',\n",
        "        # '53':'Real Estate Rental and Leasing',\n",
        "        # '54':'Professional, Scientific, and Technical Services',\n",
        "        # '55':'Management of Companies and Enterprises',\n",
        "        # '56':'Administrative and Support and Waste… Services',\n",
        "        # '61':'Educational Services',\n",
        "        # '62':'Health Care and Social Assistance',\n",
        "        # '71':'Arts, Entertainment, and Recreation',\n",
        "        # '72':'Accommodation and Food Services',\n",
        "        # '81':'Other Services (except Public Administration)',\n",
        "        # '92':'Public Administration'}\n",
        "\n",
        "\n",
        "\n",
        "    def construct_sample(input):\n",
        "\n",
        "        # Load the serialized object from the pickle file\n",
        "        with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "          label_encoders = pickle.load(file)\n",
        "\n",
        "        X_test = np.zeros(20)\n",
        "        X_test[0] = label_encoders['Contracting Agency ID'].transform([input[0]])\n",
        "        X_test[1] = label_encoders['Domestic or Foreign Entity'].transform([input[5]])\n",
        "        X_test[2] = label_encoders['Is Performance Based Service Acquisition'].transform([input[6]])\n",
        "        X_test[3] = label_encoders['Type of Contract'].transform([input[1]])\n",
        "        X_test[4] = label_encoders['NAICS Code'].transform([input[2][:2]])\n",
        "        X_test[5] = label_encoders['Principal Place of Performance State Code'].transform([input[3]])\n",
        "        X_test[6] = label_encoders['Principal Place of Performance Country Name'].transform([input[4]])\n",
        "        X_test[7] = label_encoders['Country of Product or Service Origin'].transform([input[19]])\n",
        "        X_test[8] = label_encoders['Extent Competed'].transform([input[7]])\n",
        "        X_test[9] = label_encoders['Solicitation Procedures'].transform([input[8]])\n",
        "        X_test[10] = label_encoders['Local Area Set Aside'].transform([input[9]])\n",
        "        X_test[11] = label_encoders['Vendor Address State Name'].transform([input[10]])\n",
        "        X_test[12] = label_encoders['Vendor Address Country Name'].transform([input[11]])\n",
        "        X_test[13] = label_encoders['Labor Standards'].transform([input[12]])\n",
        "        X_test[14] = label_encoders['Is Vendor Business Type - For Profit Organization'].transform([input[13]])\n",
        "        X_test[15] = label_encoders['Is Vendor Business Type - All Awards'].transform([input[14]])\n",
        "        X_test[16] = label_encoders['Is Vendor Business Type - Corporate Entity, Not Tax Exempt'].transform([input[15]])\n",
        "        X_test[17] = label_encoders['Is Vendor Business Type - Manufacturer Of Goods'].transform([input[16]])\n",
        "        X_test[18] = label_encoders['Base and All Options Value (Total Contract Value)'].transform(np.array([input[17]]).reshape(-1, 1))\n",
        "        X_test[19] = label_encoders['Duration of Contract'].transform(np.array([input[18]]).reshape(-1, 1))\n",
        "\n",
        "        return X_test\n",
        "\n",
        "    def run_pred_model_business_type (select_agencyid : str,select_contracttype : str,select_naicscode : str,select_pricipalplaceofperformancestate : str,select_pricipalplaceofperformancecountry: str,select_entity: str,select_performancebasedservice: str,select_extentcompeted: str,select_solicitationprocedures: str,select_localareasetaside: str,select_vendoraddresstatename: str,select_vendoraddresscountryname: str,select_laborstandards: str,select_vendorbusinesstypeforProfit: str,select_vendorbusinesstypeallawards: str,select_vendorbusinesstypecorprateentity: str,select_vendorbusinesstypeManufactofgoods: str,select_contractvalue: str,select_contractduration: str,select_countryofprodservorigin: str):\n",
        "\n",
        "\n",
        "        #Generate prediction\n",
        "        input = [select_agencyid,select_contracttype,select_naicscode,select_pricipalplaceofperformancestate,select_pricipalplaceofperformancecountry,\n",
        "                        select_entity,select_performancebasedservice,select_extentcompeted,select_solicitationprocedures,select_localareasetaside,\n",
        "                        select_vendoraddresstatename,select_vendoraddresscountryname,select_laborstandards,select_vendorbusinesstypeforProfit,\n",
        "                        select_vendorbusinesstypeallawards,select_vendorbusinesstypecorprateentity,select_vendorbusinesstypeManufactofgoods,\n",
        "                        select_contractvalue,select_contractduration, select_countryofprodservorigin]\n",
        "\n",
        "        X_test = construct_sample(input)\n",
        "\n",
        "        # Load the serialized object from the pickle file\n",
        "        with open('/content/drive/MyDrive/IDS560/clf.pkl', 'rb') as file:\n",
        "          loaded_model = pickle.load(file)\n",
        "\n",
        "        prediction = loaded_model.predict(X_test.reshape(1, -1) )\n",
        "\n",
        "        #Predicted Business Type\n",
        "        #BusinessType = label_encoders['Business Type'].inverse_transform([prediction])\n",
        "        #return BusinessType\n",
        "\n",
        "        #Predict Probabilities\n",
        "        pred_probabilities = loaded_model.predict_proba(X_test.reshape(1, -1))\n",
        "\n",
        "\n",
        "        # Load the serialized object from the pickle file\n",
        "        with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "          label_encoders = pickle.load(file)\n",
        "\n",
        "        prob_df=pd.DataFrame(pred_probabilities, columns=label_encoders['Business Type'].classes_)\n",
        "        return prob_df\n",
        "\n",
        "    st.write(\"# Predicting the Business Type that will win the contract\")\n",
        "    st.markdown(\n",
        "        \"\"\"\n",
        "        ** You are now ready to predict which Business Type will win the contract.**\n",
        "            Please fill out the fields on the left and click on the button below to see the output.\n",
        "            You can also see the latest trands by clicking on the tableau dashboard link provided.\n",
        "\n",
        "        \"\"\"\n",
        "        )\n",
        "\n",
        "\n",
        "\n",
        "    #-- Set business type\n",
        "\n",
        "    select_agencyid = st.sidebar.text_input(label=\"Contracting Agency ID\", placeholder=\"1406\")\n",
        "\n",
        "    select_contracttype = st.sidebar.selectbox('Contract Type',\n",
        "                                        ['FIRM FIXED PRICE','TIME AND MATERIALS','LABOR HOURS','FIXED PRICE AWARD FEE','FIXED PRICE WITH ECONOMIC PRICE ADJUSTMENT','COST NO FEE','COST PLUS FIXED FEE','COST PLUS AWARD FEE','COST PLUS INCENTIVE FEE','FIXED PRICE INCENTIVE','FIXED PRICE LEVEL OF EFFORT','COST SHARING','FIXED PRICE REDETERMINATION'])\n",
        "\n",
        "    select_naicscode = st.sidebar.text_input(label=\"NAICS Code\", placeholder=\"622109\")\n",
        "\n",
        "    select_pricipalplaceofperformancestate = st.sidebar.selectbox('Principal place of performance state code', ['VA','DC','CA','MD','IN','FL','NY','MO','CO','AK','LA','ID','WY','SD','MT','OR','WA','VT','PA','NM','NJ','IL','MN','TX','WV','AL','PR','KY','SC','NC','OK','GA','AR','MS','NE','MI','OH','IA','DE','NH','KS','WI','AZ','TN','CT','MA','HI','UT','RI','ME','ND','NV','AS','UGANDA','GU','FRANCE','VI','VIETNAM','CANADA','JAPAN','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_pricipalplaceofperformancecountry = st.sidebar.selectbox('Principal place of performance country name',\n",
        "                                        ['UNITED STATES','UGANDA','FRANCE','VIETNAM','CANADA','JAPAN','UNITED KINGDOM','BAHRAIN','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_entity = st.sidebar.selectbox(\"Domestic or Foreign Entity\",['U.S. OWNED BUSINESS','OTHER U.S. ENTITY (E.G. GOVERNMENT)','FOREIGN-OWNED BUSINESS INCORPORATED IN THE U.S.','FOREIGN-OWNED BUSINESS NOT INCORPORATED IN THE U.S.','OTHER FOREIGN ENTITY (E.G. FOREIGN GOVERNMENT)'])\n",
        "\n",
        "    select_performancebasedservice = st.sidebar.radio(\"Performance Based Service Acquisition\",('NO - SERVICE WHERE PBA IS NOT USED.','YES - SERVICE WHERE PBA IS USED.','NOT APPLICABLE'))\n",
        "\n",
        "    select_extentcompeted = st.sidebar.selectbox('Extent Competed',\n",
        "                                        ['FULL AND OPEN COMPETITION','NOT COMPETED UNDER SAP','FULL AND OPEN COMPETITION AFTER EXCLUSION OF SOURCES','NOT COMPETED','COMPETED UNDER SAP','NOT AVAILABLE FOR COMPETITION'])\n",
        "\n",
        "    select_solicitationprocedures = st.sidebar.selectbox('Solicitation Procedures',\n",
        "                                        ['SUBJECT TO MULTIPLE AWARD FAIR OPPORTUNITY','SIMPLIFIED ACQUISITION','NEGOTIATED PROPOSAL/QUOTE','ONLY ONE SOURCE','ALTERNATIVE SOURCES','SEALED BID','ARCHITECT-ENGINEER FAR 6.102','BASIC RESEARCH','TWO STEP'])\n",
        "\n",
        "    select_localareasetaside = st.sidebar.radio(\"Local Area Set Aside\",('YES','NO'))\n",
        "\n",
        "    select_vendoraddresstatename = st.sidebar.selectbox('Vendor Address State',\n",
        "                                        ['ILLINOIS','ARIZONA','TEXAS','CALIFORNIA','NEW YORK','NEW JERSEY','NORTH CAROLINA'])\n",
        "\n",
        "    select_vendoraddresscountryname = st.sidebar.selectbox('Vendor address country name',\n",
        "                                        ['UNITED STATES','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_laborstandards = st.sidebar.radio(\"Labor Standards\",('YES','NO','NOT APPLICABLE'))\n",
        "\n",
        "    select_vendorbusinesstypeforProfit = st.sidebar.radio(\"Is Vendor Business type - For Profit Organisation\",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypeallawards = st.sidebar.radio(\"Is Vendor Business type - All Awards \",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypecorprateentity = st.sidebar.radio(\"Is Vendor Business type - Corporate Entity, Not tax Exempt\",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypeManufactofgoods = st.sidebar.radio(\"Is Vendor Business type - Manufacturer of Goods\",('YES','NO'))\n",
        "\n",
        "    select_contractvalue = st.sidebar.text_input(label=\"Total Contract Value\", placeholder=\"$25,000,000\")\n",
        "\n",
        "    select_contractduration = st.sidebar.text_input(label=\"Contract Duration(in days)\", placeholder=\"365\")\n",
        "\n",
        "    select_countryofprodservorigin = st.sidebar.selectbox('Country of Product or Service Origin',\n",
        "                                        ['UNITED STATES','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "\n",
        "    html_temp = \"<div class='tableauPlaceholder' id='viz1711381846728' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='IDS_560_dashboard&#47;Dashboard1' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1711381846728');                    var vizElement = divElement.getElementsByTagName('object')[0];                 if ( divElement.offsetWidth > 800 ) { vizElement.style.width='2850px';vizElement.style.height='1727px';}else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='2850px';vizElement.style.height='1727px';} else { vizElement.style.width='100%';vizElement.style.height='2077px';}               var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>\"\n",
        "    components.html(html_temp)\n",
        "\n",
        "    def redirect_button(url: str, text: str= None, color=\"#FD504D\"):\n",
        "      st.markdown(\n",
        "      f\"\"\"\n",
        "      <a href=\"{url}\" target=\"_self\">\n",
        "          <div style=\"\n",
        "              display: inline-block;\n",
        "              padding: 0.5em 1em;\n",
        "              color: #FFFFFF;\n",
        "              background-color: {color};\n",
        "              border-radius: 3px;\n",
        "              text-decoration: none;\">\n",
        "              {text}\n",
        "          </div>\n",
        "      </a>\n",
        "      \"\"\",\n",
        "      unsafe_allow_html=True\n",
        "      )\n",
        "\n",
        "      redirect_button(url,\"this leads to the tableau dashboard\")\n",
        "\n",
        "    def main():\n",
        "      import pickle\n",
        "      # Load the serialized object from the pickle file\n",
        "      with open('/content/drive/MyDrive/IDS560/clf.pkl', 'rb') as file:\n",
        "        loaded_model = pickle.load(file)\n",
        "\n",
        "      # # Load the serialized object from the pickle file\n",
        "      with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "        label_encoders = pickle.load(file)\n",
        "\n",
        "    html_temp = \"<div class='tableauPlaceholder' id='viz1710733360364' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='IDS_560_dashboard&#47;Dashboard1' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1710733360364');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.minWidth='1620px';vizElement.style.maxWidth='1720px';vizElement.style.width='100%';vizElement.style.minHeight='818px';vizElement.style.maxHeight='910px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.minWidth='1620px';vizElement.style.maxWidth='1720px';vizElement.style.width='100%';vizElement.style.minHeight='818px';vizElement.style.maxHeight='910px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='1250px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>\"\n",
        "    components.html(html_temp)\n",
        "\n",
        "    output_html= \"\"\"\n",
        "    <div style = \"background-color:#F08080;padding:10px >\n",
        "    <h2 style = \"color:black; text-align: center;\"> Business Type Won</h2>\n",
        "    </div>\n",
        "    \"\"\"\n",
        "\n",
        "    if st.button (\"Predict the business type to win the contract\"):\n",
        "      output = run_pred_model_business_type(select_agencyid,select_contracttype,select_naicscode,select_pricipalplaceofperformancestate,\n",
        "                    select_pricipalplaceofperformancecountry,select_entity,select_performancebasedservice,select_extentcompeted,select_solicitationprocedures,\n",
        "                    select_localareasetaside,select_vendoraddresstatename,select_vendoraddresscountryname,select_laborstandards,\n",
        "                    select_vendorbusinesstypeforProfit,select_vendorbusinesstypeallawards,select_vendorbusinesstypecorprateentity,\n",
        "                    select_vendorbusinesstypeManufactofgoods,select_contractvalue,select_contractduration,select_countryofprodservorigin)\n",
        "\n",
        "          #st.success('The business that will win the contract is{}'.format(output))\n",
        "          #st.table(output)\n",
        "      st.dataframe(output.style.highlight_max(axis=1))\n",
        "\n",
        "    if __name__ == \"__main__\":\n",
        "          main()\n",
        "\n",
        "def contract_value_predict():\n",
        "    import pandas as pd\n",
        "    import numpy as np\n",
        "    import pickle\n",
        "    import matplotlib.pyplot as plt\n",
        "    import requests, os\n",
        "    import base64\n",
        "    import streamlit as st\n",
        "    import streamlit.components.v1 as components\n",
        "\n",
        "\n",
        "\n",
        "    def run_pred_model_business_type (select_businesstype: str,select_agencyid : str,select_contracttype : str,select_naicscode : str,select_pricipalplaceofperformancestate : str,\n",
        "                    select_pricipalplaceofperformancecountry: str,select_entity: str,select_performancebasedservice: str,select_extentcompeted: str,select_solicitationprocedures: str,\n",
        "                    select_localareasetaside: str,select_vendoraddresstatename: str,select_vendoraddresscountryname: str,select_laborstandards: str,\n",
        "                    select_vendorbusinesstypeforProfit: str,select_vendorbusinesstypeallawards: str,select_vendorbusinesstypecorprateentity: str,\n",
        "                    select_vendorbusinesstypeManufactofgoods: str,select_contractvalue: str,select_contractduration: str):\n",
        "        \"\"\"Generate prediction.\"\"\"\n",
        "\n",
        "\n",
        "\n",
        "    #-- Set business type\n",
        "\n",
        "    select_businesstype = st.sidebar.selectbox('What business type do you want to see?',\n",
        "                                        ['Women Owned','Veteran Owned', 'Small Business'])\n",
        "\n",
        "    select_agencyid = st.sidebar.text_input(label=\"Contracting Agency ID\", placeholder=\"1406\")\n",
        "\n",
        "    select_contracttype = st.sidebar.selectbox('Contract Type',\n",
        "                                        ['FIRM FIXED PRICE','TIME AND MATERIALS','LABOR HOURS','FIXED PRICE AWARD FEE','FIXED PRICE WITH ECONOMIC PRICE ADJUSTMENT','COST NO FEE','COST PLUS FIXED FEE','COST PLUS AWARD FEE','COST PLUS INCENTIVE FEE','FIXED PRICE INCENTIVE','FIXED PRICE LEVEL OF EFFORT','COST SHARING','FIXED PRICE REDETERMINATION'])\n",
        "\n",
        "    select_naicscode = st.sidebar.text_input(label=\"NAICS Code\", placeholder=\"622109\")\n",
        "\n",
        "    select_pricipalplaceofperformancestate = st.sidebar.selectbox('Principal place of performance state code', ['VA','DC','CA','MD','IN','FL','NY','MO','CO','AK','LA','ID','WY','SD','MT','OR','WA','VT','PA','NM','NJ','IL','MN','TX','WV','AL','PR','KY','SC','NC','OK','GA','AR','MS','NE','MI','OH','IA','DE','NH','KS','WI','AZ','TN','CT','MA','HI','UT','RI','ME','ND','NV','AS','UGANDA','GU','FRANCE','VI','VIETNAM','CANADA','JAPAN','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_pricipalplaceofperformancecountry = st.sidebar.selectbox('Principal place of performance country name',\n",
        "                                        ['UNITED STATES','UGANDA','FRANCE','VIETNAM','CANADA','JAPAN','UNITED KINGDOM','BAHRAIN','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_entity = st.sidebar.selectbox(\"Domestic or Foreign Entity\",['U.S. OWNED BUSINESS','OTHER U.S. ENTITY (E.G. GOVERNMENT)','FOREIGN-OWNED BUSINESS INCORPORATED IN THE U.S.','FOREIGN-OWNED BUSINESS NOT INCORPORATED IN THE U.S.','OTHER FOREIGN ENTITY (E.G. FOREIGN GOVERNMENT)'])\n",
        "\n",
        "    select_performancebasedservice = st.sidebar.radio(\"Performance Based Service Acquisition\",('NO - SERVICE WHERE PBA IS NOT USED.','YES - SERVICE WHERE PBA IS USED.','NOT APPLICABLE'))\n",
        "\n",
        "    select_extentcompeted = st.sidebar.selectbox('Extent Competed',\n",
        "                                        ['FULL AND OPEN COMPETITION','NOT COMPETED UNDER SAP','FULL AND OPEN COMPETITION AFTER EXCLUSION OF SOURCES','NOT COMPETED','COMPETED UNDER SAP','NOT AVAILABLE FOR COMPETITION'])\n",
        "\n",
        "    select_solicitationprocedures = st.sidebar.selectbox('Solicitation Procedures',\n",
        "                                        ['SUBJECT TO MULTIPLE AWARD FAIR OPPORTUNITY','SIMPLIFIED ACQUISITION','NEGOTIATED PROPOSAL/QUOTE','ONLY ONE SOURCE','ALTERNATIVE SOURCES','SEALED BID','ARCHITECT-ENGINEER FAR 6.102','BASIC RESEARCH','TWO STEP'])\n",
        "\n",
        "    select_localareasetaside = st.sidebar.radio(\"Local Area Set Aside\",('YES','NO'))\n",
        "\n",
        "    select_vendoraddresstatename = st.sidebar.selectbox('Vendor Address State',\n",
        "                                        ['ILLINOIS','ARIZONA','TEXAS','CALIFORNIA','NEW YORK','NEW JERSEY','NORTH CAROLINA'])\n",
        "\n",
        "    select_vendoraddresscountryname = st.sidebar.selectbox('Vendor address country name',\n",
        "                                        ['UNITED STATES','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_laborstandards = st.sidebar.radio(\"Labor Standards\",('YES','NO','NOT APPLICABLE'))\n",
        "\n",
        "    select_vendorbusinesstypeforProfit = st.sidebar.radio(\"Is Vendor Business type - For Profit Organisation\",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypeallawards = st.sidebar.radio(\"Is Vendor Business type - All Awards \",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypecorprateentity = st.sidebar.radio(\"Is Vendor Business type - Corporate Entity, Not tax Exempt\",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypeManufactofgoods = st.sidebar.radio(\"Is Vendor Business type - Manufacturer of Goods\",('YES','NO'))\n",
        "\n",
        "    select_contractduration = st.sidebar.text_input(label=\"Contract Duration(in days)\", placeholder=\"365\")\n",
        "\n",
        "    select_countryofprodservorigin = st.sidebar.selectbox('Country of Product or Service Origin',\n",
        "                                        ['UNITED STATES','INDIA','CANADA','MEXICO'])\n",
        "    html_temp = \"<div class='tableauPlaceholder' id='viz1711381846728' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='IDS_560_dashboard&#47;Dashboard1' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1711381846728');                    var vizElement = divElement.getElementsByTagName('object')[0];                 if ( divElement.offsetWidth > 800 ) { vizElement.style.width='2850px';vizElement.style.height='1727px';}else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='2850px';vizElement.style.height='1727px';} else { vizElement.style.width='100%';vizElement.style.height='2077px';}               var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>\"\n",
        "    components.html(html_temp)\n",
        "\n",
        "\n",
        "def contract_duration_predict():\n",
        "    import pandas as pd\n",
        "    import numpy as np\n",
        "    import pickle\n",
        "    import matplotlib.pyplot as plt\n",
        "    import requests, os\n",
        "    import base64\n",
        "    import streamlit as st\n",
        "    import streamlit.components.v1 as components\n",
        "\n",
        "\n",
        "          # def first_19_inputs():\n",
        "              # with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "              #         label_encoders = pickle.load(file)\n",
        "\n",
        "              # X_test = np.zeros(19)\n",
        "              # X_test[0] = label_encoders['Contracting Agency ID'].transform([input[0]])\n",
        "              # X_test[1] = label_encoders['Domestic or Foreign Entity'].transform([input[5]])\n",
        "              # X_test[2] = label_encoders['Is Performance Based Service Acquisition'].transform([input[6]])\n",
        "              # X_test[3] = label_encoders['Type of Contract'].transform([input[1]])\n",
        "              # X_test[4] = label_encoders['NAICS Code'].transform([input[2][:2]])\n",
        "              # X_test[5] = label_encoders['Principal Place of Performance State Code'].transform([input[3]])\n",
        "              # X_test[6] = label_encoders['Principal Place of Performance Country Name'].transform([input[4]])\n",
        "              # X_test[7] = label_encoders['Country of Product or Service Origin'].transform([input[19]])\n",
        "              # X_test[8] = label_encoders['Extent Competed'].transform([input[7]])\n",
        "              # X_test[9] = label_encoders['Solicitation Procedures'].transform([input[8]])\n",
        "              # X_test[10] = label_encoders['Local Area Set Aside'].transform([input[9]])\n",
        "              # X_test[11] = label_encoders['Vendor Address State Name'].transform([input[10]])\n",
        "              # X_test[12] = label_encoders['Vendor Address Country Name'].transform([input[11]])\n",
        "              # X_test[13] = label_encoders['Labor Standards'].transform([input[12]])\n",
        "              # X_test[14] = label_encoders['Is Vendor Business Type - For Profit Organization'].transform([input[13]])\n",
        "              # X_test[15] = label_encoders['Is Vendor Business Type - All Awards'].transform([input[14]])\n",
        "              # X_test[16] = label_encoders['Is Vendor Business Type - Corporate Entity, Not Tax Exempt'].transform([input[15]])\n",
        "              # X_test[17] = label_encoders['Is Vendor Business Type - Manufacturer Of Goods'].transform([input[16]])\n",
        "              # X_test[18] = label_encoders['Business Type'].transform([input[16]])\n",
        "              # X_test[19] = label_encoders['Base and All Options Value (Total Contract Value)'].transform(np.array([input[17]]).reshape(-1, 1))\n",
        "\n",
        "              # return X_test\n",
        "\n",
        "    def construct_sample_duration(input):\n",
        "\n",
        "        # # Load the serialized object from the pickle file\n",
        "        # with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "        #   label_encoders = pickle.load(file)\n",
        "\n",
        "        # #Get rid of the repetition of the lines - defined at the bottom of this cell\n",
        "        # X_test = first_19_inputs()\n",
        "        # #appending the last input - \"Business Type\"\n",
        "        # X_test = np.append(X_test, label_encoders['Business Type'].transform(np.array([input[18]]).reshape(-1, 1)))\n",
        "\n",
        "        # return X_test\n",
        "\n",
        "        # Load the serialized object from the pickle file\n",
        "        with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "          label_encoders = pickle.load(file)\n",
        "\n",
        "        X_test = np.zeros(20)\n",
        "        X_test[0] = label_encoders['Contracting Agency ID'].transform([input[0]])\n",
        "        X_test[1] = label_encoders['Domestic or Foreign Entity'].transform([input[5]])\n",
        "        X_test[2] = label_encoders['Is Performance Based Service Acquisition'].transform([input[6]])\n",
        "        X_test[3] = label_encoders['Type of Contract'].transform([input[1]])\n",
        "        X_test[4] = label_encoders['NAICS Code'].transform([input[2][:2]])\n",
        "        X_test[5] = label_encoders['Principal Place of Performance State Code'].transform([input[3]])\n",
        "        X_test[6] = label_encoders['Principal Place of Performance Country Name'].transform([input[4]])\n",
        "        X_test[7] = label_encoders['Country of Product or Service Origin'].transform([input[18]])\n",
        "        X_test[8] = label_encoders['Extent Competed'].transform([input[7]])\n",
        "        X_test[9] = label_encoders['Solicitation Procedures'].transform([input[8]])\n",
        "        X_test[10] = label_encoders['Local Area Set Aside'].transform([input[9]])\n",
        "        X_test[11] = label_encoders['Vendor Address State Name'].transform([input[10]])\n",
        "        X_test[12] = label_encoders['Vendor Address Country Name'].transform([input[11]])\n",
        "        X_test[13] = label_encoders['Labor Standards'].transform([input[12]])\n",
        "        X_test[14] = label_encoders['Is Vendor Business Type - For Profit Organization'].transform([input[13]])\n",
        "        X_test[15] = label_encoders['Is Vendor Business Type - All Awards'].transform([input[14]])\n",
        "        X_test[16] = label_encoders['Is Vendor Business Type - Corporate Entity, Not Tax Exempt'].transform([input[15]])\n",
        "        X_test[17] = label_encoders['Is Vendor Business Type - Manufacturer Of Goods'].transform([input[16]])\n",
        "        X_test[18] = label_encoders['Business Type'].transform([input[19]])\n",
        "        X_test[19] = label_encoders['Base and All Options Value (Total Contract Value)'].transform(np.array([input[17]]).reshape(-1, 1))\n",
        "\n",
        "        return X_test\n",
        "\n",
        "    def run_pred_duration (select_agencyid : str,select_contracttype : str,select_naicscode : str,select_pricipalplaceofperformancestate : str,\n",
        "                       select_pricipalplaceofperformancecountry: str,select_entity: str,select_performancebasedservice: str,select_extentcompeted: str,\n",
        "                       select_solicitationprocedures: str,select_localareasetaside: str,select_vendoraddresstatename: str,select_vendoraddresscountryname: str,\n",
        "                       select_laborstandards: str,select_vendorbusinesstypeforProfit: str,select_vendorbusinesstypeallawards: str,select_vendorbusinesstypecorprateentity: str,\n",
        "                       select_vendorbusinesstypeManufactofgoods: str,select_contractvalue: str,select_countryofprodservorigin: str,select_businesstype: str):\n",
        "\n",
        "          #Generate prediction\n",
        "      input = [select_agencyid,select_contracttype,select_naicscode,select_pricipalplaceofperformancestate,select_pricipalplaceofperformancecountry,\n",
        "                          select_entity,select_performancebasedservice,select_extentcompeted,select_solicitationprocedures,select_localareasetaside,\n",
        "                          select_vendoraddresstatename,select_vendoraddresscountryname,select_laborstandards,select_vendorbusinesstypeforProfit,\n",
        "                          select_vendorbusinesstypeallawards,select_vendorbusinesstypecorprateentity,select_vendorbusinesstypeManufactofgoods,\n",
        "                          select_contractvalue,select_countryofprodservorigin,select_businesstype]\n",
        "\n",
        "      X_test = construct_sample_duration(input)\n",
        "\n",
        "          # Load the serialized object from the pickle file -> change for duration model\n",
        "          # for durration writing would need to inlude this in the other script with the model:\n",
        "              # with open('dur_xgb.pkl', 'wb') as file:\n",
        "              #   pickle.dump(xgb_r, file)\n",
        "\n",
        "      # Load the serialized object from the pickle file -> change for duration model\n",
        "      with open('/content/drive/MyDrive/IDS560/dur_xgb.pkl', 'rb') as file:\n",
        "        loaded_model = pickle.load(file)\n",
        "\n",
        "      # Load the serialized object from the pickle file\n",
        "      with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "        label_encoders = pickle.load(file)\n",
        "\n",
        "      #Regression of the Duration - I think reshaping is not necessary\n",
        "      prediction = loaded_model.predict(X_test.reshape(1, -1))\n",
        "\n",
        "      Contract_Duration = label_encoders['Duration of Contract'].inverse_transform([prediction])\n",
        "      return Contract_Duration\n",
        "\n",
        "    st.write(\"# Predicting the Duration of contract\")\n",
        "    st.markdown(\n",
        "        \"\"\"\n",
        "        ** You are now ready to predict which Business Type will win the contract.**\n",
        "            Please fill out the fields on the left and click on the button below to see the output.\n",
        "            You can also see the latest trands by clicking on the tableau dashboard link provided.\n",
        "\n",
        "        \"\"\"\n",
        "        )\n",
        "\n",
        "    #-- Set Duration of contract\n",
        "    select_businesstype = st.sidebar.selectbox('What business type do you want to see?',\n",
        "                                    ['Others',\t'Is Vendor Business Type - Limited Liability Corporation',\t'Is Vendor Business Type - Subchapter S Corporation',\n",
        "                                     'Is Vendor Business Type - Self-Certified Small Disadvantaged Business',\t'Is Vendor Business Type - Women-Owned Business',\n",
        "                                     'Is Vendor Business Type - The AbilityOne Program',\t'Is Vendor Business Type - Partnership or Limited Liability Partnership',\n",
        "                                     'Is Vendor Business Type - Foreign Owned',\t'Is Vendor Business Type - Veteran-Owned Business',\n",
        "                                     'Is Vendor Business Type - Hispanic American Owned',\t'Is Vendor Business Type - Contracts',\n",
        "                                     'Is Vendor Business Type - 8A Program Participant',\t'Is Vendor Business Type - Native American Owned',\n",
        "                                     'Is Vendor Business Type - Sole Proprietorship',\t'Is Vendor Business Type - Subcontinent Asian (Asian-Indian) American Owned',\n",
        "                                     'Is Vendor Business Type - Black American Owned',\t'Is Vendor Business Type - HUBZone Firm',\n",
        "                                     'Is Vendor Business Type - Asian-Pacific American Owned',\n",
        "                                     'Is Vendor Business Type - DoT Certified Disadvantaged Business Enterprise',\n",
        "                                     'Is Vendor Business Type - Other Not For Profit Organization',\t'Is Vendor Business Type - Other Minority-Owned'])\n",
        "\n",
        "    select_agencyid = st.sidebar.text_input(label=\"Contracting Agency ID\", placeholder=\"1406\")\n",
        "\n",
        "    select_contracttype = st.sidebar.selectbox('Contract Type',\n",
        "                                        ['FIRM FIXED PRICE','TIME AND MATERIALS','LABOR HOURS','FIXED PRICE AWARD FEE','FIXED PRICE WITH ECONOMIC PRICE ADJUSTMENT','COST NO FEE','COST PLUS FIXED FEE','COST PLUS AWARD FEE','COST PLUS INCENTIVE FEE','FIXED PRICE INCENTIVE','FIXED PRICE LEVEL OF EFFORT','COST SHARING','FIXED PRICE REDETERMINATION'])\n",
        "\n",
        "    select_naicscode = st.sidebar.text_input(label=\"NAICS Code\", placeholder=\"622109\")\n",
        "\n",
        "    select_pricipalplaceofperformancestate = st.sidebar.selectbox('Principal place of performance state code', ['VA','DC','CA','MD','IN','FL','NY','MO','CO','AK','LA','ID','WY','SD','MT','OR','WA','VT','PA','NM','NJ','IL','MN','TX','WV','AL','PR','KY','SC','NC','OK','GA','AR','MS','NE','MI','OH','IA','DE','NH','KS','WI','AZ','TN','CT','MA','HI','UT','RI','ME','ND','NV','AS','UGANDA','GU','FRANCE','VI','VIETNAM','CANADA','JAPAN','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_pricipalplaceofperformancecountry = st.sidebar.selectbox('Principal place of performance country name',\n",
        "                                        ['UNITED STATES','UGANDA','FRANCE','VIETNAM','CANADA','JAPAN','UNITED KINGDOM','BAHRAIN','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_entity = st.sidebar.selectbox(\"Domestic or Foreign Entity\",['U.S. OWNED BUSINESS','OTHER U.S. ENTITY (E.G. GOVERNMENT)','FOREIGN-OWNED BUSINESS INCORPORATED IN THE U.S.','FOREIGN-OWNED BUSINESS NOT INCORPORATED IN THE U.S.','OTHER FOREIGN ENTITY (E.G. FOREIGN GOVERNMENT)'])\n",
        "\n",
        "    select_performancebasedservice = st.sidebar.radio(\"Performance Based Service Acquisition\",('NO - SERVICE WHERE PBA IS NOT USED.','YES - SERVICE WHERE PBA IS USED.','NOT APPLICABLE'))\n",
        "\n",
        "    select_extentcompeted = st.sidebar.selectbox('Extent Competed',\n",
        "                                        ['FULL AND OPEN COMPETITION','NOT COMPETED UNDER SAP','FULL AND OPEN COMPETITION AFTER EXCLUSION OF SOURCES','NOT COMPETED','COMPETED UNDER SAP','NOT AVAILABLE FOR COMPETITION'])\n",
        "\n",
        "    select_solicitationprocedures = st.sidebar.selectbox('Solicitation Procedures',\n",
        "                                        ['SUBJECT TO MULTIPLE AWARD FAIR OPPORTUNITY','SIMPLIFIED ACQUISITION','NEGOTIATED PROPOSAL/QUOTE','ONLY ONE SOURCE','ALTERNATIVE SOURCES','SEALED BID','ARCHITECT-ENGINEER FAR 6.102','BASIC RESEARCH','TWO STEP'])\n",
        "\n",
        "    select_localareasetaside = st.sidebar.radio(\"Local Area Set Aside\",('YES','NO'))\n",
        "\n",
        "    select_vendoraddresstatename = st.sidebar.selectbox('Vendor Address State',\n",
        "                                        ['ILLINOIS','ARIZONA','TEXAS','CALIFORNIA','NEW YORK','NEW JERSEY','NORTH CAROLINA'])\n",
        "\n",
        "    select_vendoraddresscountryname = st.sidebar.selectbox('Vendor address country name',\n",
        "                                        ['UNITED STATES','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    select_laborstandards = st.sidebar.radio(\"Labor Standards\",('YES','NO','NOT APPLICABLE'))\n",
        "\n",
        "    select_vendorbusinesstypeforProfit = st.sidebar.radio(\"Is Vendor Business type - For Profit Organisation\",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypeallawards = st.sidebar.radio(\"Is Vendor Business type - All Awards \",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypecorprateentity = st.sidebar.radio(\"Is Vendor Business type - Corporate Entity, Not tax Exempt\",('YES','NO'))\n",
        "\n",
        "    select_vendorbusinesstypeManufactofgoods = st.sidebar.radio(\"Is Vendor Business type - Manufacturer of Goods\",('YES','NO'))\n",
        "\n",
        "    select_contractvalue = st.sidebar.text_input(label=\"Total Contract Value\", placeholder=\"$25,000,000\")\n",
        "\n",
        "    select_countryofprodservorigin = st.sidebar.selectbox('Country of Product or Service Origin',\n",
        "                                        ['UNITED STATES','INDIA','CANADA','MEXICO'])\n",
        "\n",
        "    html_temp1 = \"<div class='tableauPlaceholder' id='viz1711381846728' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='IDS_560_dashboard&#47;Dashboard1' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1711381846728');                    var vizElement = divElement.getElementsByTagName('object')[0];                 if ( divElement.offsetWidth > 800 ) { vizElement.style.width='2850px';vizElement.style.height='1727px';}else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='2850px';vizElement.style.height='1727px';} else { vizElement.style.width='100%';vizElement.style.height='2077px';}               var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>\"\n",
        "    components.html(html_temp1)\n",
        "\n",
        "    def redirect_button(url: str, text: str= None, color=\"#FD504D\"):\n",
        "      st.markdown(\n",
        "      f\"\"\"\n",
        "      <a href=\"{url}\" target=\"_self\">\n",
        "          <div style=\"\n",
        "              display: inline-block;\n",
        "              padding: 0.5em 1em;\n",
        "              color: #FFFFFF;\n",
        "              background-color: {color};\n",
        "              border-radius: 3px;\n",
        "              text-decoration: none;\">\n",
        "              {text}\n",
        "          </div>\n",
        "      </a>\n",
        "      \"\"\",\n",
        "      unsafe_allow_html=True\n",
        "      )\n",
        "\n",
        "      redirect_button(url,\"this leads to the tableau dashboard\")\n",
        "\n",
        "    def main():\n",
        "      import pickle\n",
        "      # Load the serialized object from the pickle file\n",
        "      with open('/content/drive/MyDrive/IDS560/dur_xgb.pkl', 'rb') as file:\n",
        "        loaded_model = pickle.load(file)\n",
        "\n",
        "      # Load the serialized object from the pickle file\n",
        "      with open('/content/drive/MyDrive/IDS560/label_encoder.pkl', 'rb') as file:\n",
        "        label_encoders = pickle.load(file)\n",
        "\n",
        "    html_temp = \"<div class='tableauPlaceholder' id='viz1710733360364' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='IDS_560_dashboard&#47;Dashboard1' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ID&#47;IDS_560_dashboard&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1710733360364');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.minWidth='1620px';vizElement.style.maxWidth='1720px';vizElement.style.width='100%';vizElement.style.minHeight='818px';vizElement.style.maxHeight='910px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.minWidth='1620px';vizElement.style.maxWidth='1720px';vizElement.style.width='100%';vizElement.style.minHeight='818px';vizElement.style.maxHeight='910px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='1250px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>\"\n",
        "    components.html(html_temp)\n",
        "\n",
        "    if st.button (\"Predict the Duration of the contract\"):\n",
        "      output = run_pred_duration(select_agencyid,select_contracttype,select_naicscode,select_pricipalplaceofperformancestate,\n",
        "                select_pricipalplaceofperformancecountry,select_entity,select_performancebasedservice,select_extentcompeted,select_solicitationprocedures,\n",
        "                select_localareasetaside,select_vendoraddresstatename,select_vendoraddresscountryname,select_laborstandards,\n",
        "                select_vendorbusinesstypeforProfit,select_vendorbusinesstypeallawards,select_vendorbusinesstypecorprateentity,\n",
        "                select_vendorbusinesstypeManufactofgoods,select_contractvalue,select_countryofprodservorigin,select_businesstype)\n",
        "\n",
        "      st.success('The duration of the contract is {} days'.format(int(output)))\n",
        "      # #st.table(output)\n",
        "      # st.dataframe(output.style.highlight_max(axis=1))\n",
        "\n",
        "    if __name__ == \"__main__\":\n",
        "       main()\n",
        "\n",
        "page_names_to_funcs = {\n",
        "    \"—\": intro,\n",
        "    \"Predict Business Type\": business_type_predict,\n",
        "    \"Predict Contract Value\": contract_value_predict,\n",
        "    \"Predict Contract Duration\": contract_duration_predict\n",
        "}\n",
        "\n",
        "demo_name = st.sidebar.selectbox(\"Choose a demo\", page_names_to_funcs.keys())\n",
        "page_names_to_funcs[demo_name]()"
      ]
    }
  ]
}